/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./app/**/*.{ts,tsx}", "./lib/**/*.{ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#ffe087",
        "on-background": "#1a1c1d",
        "tertiary-fixed-dim": "#75d1ff",
        "surface-container-high": "#e8e8ea",
        "surface-bright": "#f9f9fb",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#005572",
        background: "#f9f9fb",
        "on-primary": "#ffffff",
        "surface-container-low": "#f3f3f5",
        "surface-container-highest": "#e2e2e4",
        secondary: "#735c00",
        "error-container": "#ffdad6",
        "inverse-surface": "#2f3132",
        "tertiary-fixed": "#c2e8ff",
        "on-secondary-fixed": "#241a00",
        "secondary-fixed-dim": "#ebc23e",
        "surface-variant": "#e2e2e4",
        "inverse-primary": "#ebb2ff",
        "surface-dim": "#d9dadc",
        "on-error": "#ffffff",
        "on-tertiary-container": "#60ccff",
        "on-tertiary-fixed": "#001e2b",
        "on-primary-fixed-variant": "#721199",
        "on-primary-container": "#e8aaff",
        "inverse-on-surface": "#f0f0f2",
        "surface-container": "#eeeef0",
        "primary-fixed-dim": "#ebb2ff",
        "primary-container": "#7b1fa2",
        error: "#ba1a1a",
        primary: "#5e0081",
        "outline-variant": "#d2c1d3",
        "on-primary-fixed": "#320047",
        "surface-container-lowest": "#ffffff",
        "secondary-container": "#fdd34d",
        "on-secondary-fixed-variant": "#574500",
        "on-error-container": "#93000a",
        tertiary: "#003d53",
        "on-surface": "#1a1c1d",
        "on-secondary-container": "#725b00",
        "surface-tint": "#8c33b3",
        "on-secondary": "#ffffff",
        outline: "#807382",
        "on-surface-variant": "#4e4351",
        "primary-fixed": "#f8d8ff",
        "on-tertiary-fixed-variant": "#004d67",
        surface: "#f9f9fb",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        "margin-desktop": "48px",
        "gutter-mobile": "16px",
        "max-content-width": "1120px",
        "gutter-desktop": "24px",
        "margin-mobile": "16px",
      },
      fontFamily: {
        "headline-lg": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
      },
      fontSize: {
        "headline-lg": [
          "32px",
          { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "800" },
        ],
        "headline-md": ["20px", { lineHeight: "1.4", fontWeight: "700" }],
        "label-md": [
          "14px",
          { lineHeight: "1.2", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "headline-lg-mobile": ["24px", { lineHeight: "1.2", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "500" }],
        "label-sm": ["12px", { lineHeight: "1.2", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
